// Canned form data for the "Fill Demo Data" button — a fully realistic, complete example (an
// employee onboarding dashboard with a narrow, deliberately-scoped AI capability) so a demo can go
// from blank form to Generate Documents in one click, instead of typing out every field live. Every
// field a real submission would need is filled in; nothing is left for auto-generate. Shaped as a
// DraftFormState (raw editable strings, same as what typing into the form produces) so it drops
// straight into RequestForm's state.

import { DraftFormState } from "./formLogic";

export const DEMO_DRAFT: DraftFormState = {
  project_name: "Employee Onboarding Dashboard",
  doc_id_acronym: "EOD",
  problem_statement:
    "New joinees currently receive onboarding through scattered emails, ad-hoc Slack messages and verbal instructions. There is no single place that tells them what to do, by when, which certifications are mandatory, whom to connect with, or where to go for IT access and support. Managers rebuild the same onboarding task list from scratch for every hire, which is slow and inconsistent. As a result, ramp-up time varies widely between joinees, mandatory compliance certifications are missed or completed late, and IT and HR field the same repetitive questions from every new hire.",
  business_context:
    "Onboarding is currently a manual, manager-dependent process with no system of record. Nothing is tracked, so no one can answer how far along a new hire is until someone asks them directly. The organisation wants a lightweight internal web application with exactly two roles — Manager and New Joinee — that centralises the onboarding plan, certifications, people to connect with, and a static information hub for IT, HR and access queries. AI is used deliberately narrowly: a single capability that expands a manager's short free-text brief into a structured draft task list, which the manager must review and approve before it reaches the joinee. All other content is entered manually by the manager or seeded as static reference data. This keeps the system predictable, auditable and cheap to run, and keeps accountability with the manager rather than the model.",
  decision_audience: "Engineering Manager (product owner and approver), Head of HR, IT Operations Lead, Information Security reviewer",

  scope_in: [
    "Two roles only: MANAGER and JOINEE, with a manager-to-joinee mapping",
    "Authentication via corporate OIDC identity provider (Google Workspace / Azure AD)",
    "Manager creates an onboarding plan per joinee, anchored to the joinee's start date",
    "AI-assisted task generation: manager free-text brief expanded into a structured draft task list",
    "Mandatory manager review, edit and approval of every AI-generated task before it becomes visible to the joinee",
    "Manual task creation and editing as a first-class path, independent of AI",
    "Manager manually enters certifications: name, provider, URL, deadline, mandatory flag",
    "Manager manually enters people to connect with: name, email, title, reason",
    "Joinee dashboard: weekly task view, overdue flags, progress indicator",
    "Joinee marks tasks complete, updates certification status, uploads certification proof",
    "Joinee marks a connection as Pending, Scheduled or Met",
    "Static Information Hub, read-only to joinees, covering IT and access, accounts and tools, HR and payroll, workplace, security and compliance, and FAQ",
    "Information Hub content loaded from a versioned seed file into the database so it can be updated without a code release",
    "Search across Information Hub titles and body content",
    "Automatic due-date calculation from start date plus day offset",
    "Email reminders for upcoming and overdue items, with overdue escalation to the manager",
    "Audit trail of plan approval, task assignment and completion events",
    "Logging of every AI run including input, output, latency, token usage, acceptance and edit status",
  ].join("\n"),
  scope_permanently_excluded: [
    "Any AI use beyond task-list drafting — certifications, people recommendations, Information Hub content and progress summaries are never AI-generated in this product",
    "AI-generated content reaching a joinee without explicit manager approval",
    "Performance management, appraisal, goal-setting or rating functionality",
    "Payroll processing, compensation data or benefits enrolment",
    "Applicant tracking, recruitment or pre-offer workflow",
    "Document e-signature and contract execution",
    "Learning management system functionality — the product links out to certification providers and does not host or deliver course content",
    "Being the system of record for employee master data",
    "Joinee-to-joinee social features, feeds, messaging or chat",
    "Any external or customer-facing access; the application is internal only",
  ].join("\n"),
  constraints: [
    "Exactly two roles, MANAGER and JOINEE; no buddy, mentor or HR administrator role in v1",
    "AI is restricted to task-list drafting only; no other AI capability may be introduced without a new approval cycle",
    "AI output is always a draft and can never bypass manager approval",
    "The application must remain fully usable when the LLM provider is unavailable",
    "Authentication must use the existing corporate identity provider; no local password storage",
    "Internal network access only; no public or customer-facing exposure",
    "What employee data may be transmitted to a third-party LLM provider must be approved by Information Security before build [TBD - confirm policy]",
    "Backend must be Spring Boot with PostgreSQL to align with existing team skills and infrastructure",
    "Information Hub content accuracy is owned by IT and HR, not by the development team",
    "LLM spend must stay within an agreed monthly cap [TBD - confirm budget]",
    "Initial delivery targets a single organisation and a single language (English)",
  ].join("\n"),
  success_metrics: [
    "Percentage of joinees with an approved active plan on or before their start date — target 100%",
    "Median manager time to generate, edit and assign a complete plan — target under 20 minutes",
    "AI draft acceptance rate, measured as generated tasks assigned without deletion — target above 70%",
    "AI task edit rate, measured as assigned tasks whose fields were modified before assignment — target below 30%",
    "30-day task checklist completion rate per joinee — target above 85%",
    "Mandatory certification on-time completion rate — target above 95%",
    "Percentage of listed connections marked Met within 30 days — target above 80%",
    "Information Hub engagement, measured as unique joinees viewing at least one entry in week one — target above 90%",
    "Reduction in first-30-day access and support tickets versus baseline [TBD - confirm baseline with IT]",
    "AI generation p95 latency — target under 20 seconds, with a hard timeout at 20 seconds",
    "Percentage of AI responses failing schema validation on first attempt — target below 5%",
    "Manager weekly active usage during an active onboarding cycle — target above 80%",
    "Monthly LLM cost per onboarded joinee — target within agreed cap [TBD]",
  ].join("\n"),
  dependencies: [
    "Corporate OIDC identity provider (Google Workspace or Azure AD) with an application registration and group claims",
    "Commercial LLM provider API access, with an approved account and billing in place",
    "Information Security sign-off on the data sent to the LLM provider",
    "Information Hub source content supplied and signed off by IT Operations and HR before the Hub can ship",
    "SMTP or transactional email service for reminders and escalations",
    "PostgreSQL instance provisioned in the target environment",
    "S3-compatible object storage for certification proof uploads",
    "Deployment target and CI/CD pipeline [TBD - confirm platform]",
    "An authoritative list of active managers and their reporting lines, to seed the manager-to-joinee mapping",
    "Named content owners per Information Hub category, accountable for keeping contacts and links current",
  ].join("\n"),
  tech_stack_preferences: [
    "Backend: Java 21 with Spring Boot 3.x (Spring Web, Spring Data JPA, Spring Security, Validation)",
    "Database: PostgreSQL 16, with Flyway for schema migrations and seed data",
    "Frontend: React 18 with TypeScript, Vite and Tailwind CSS",
    "Authentication: OIDC / OAuth2 against the corporate identity provider, JWT-based session handling",
    "AI: commercial LLM API accessed through an internal abstraction layer, using structured JSON output with server-side schema validation",
    "Scheduling: Spring Scheduler, or Quartz if persistent and clustered jobs become necessary",
    "Caching: Redis for session data and AI response caching",
    "Object storage: S3-compatible store for certification proof uploads",
    "Email: transactional SMTP service",
    "API documentation: OpenAPI 3.1, contract published before frontend development begins",
    "Testing: JUnit 5 with Testcontainers for backend integration tests, Vitest and React Testing Library for frontend",
    "Deployment: Docker containers, CI/CD pipeline [TBD - confirm platform]",
    "Observability: structured JSON logging, Spring Boot Actuator health endpoints, metrics for AI latency, acceptance rate and token spend",
  ].join("\n"),
  data_flow_steps: [
    "A manager signs in through the corporate identity provider; the API validates the OIDC token and resolves the MANAGER role.",
    "The manager selects or creates a joinee record, entering job title, team and start date; a plan is created in DRAFT status.",
    "The manager types a short free-text brief describing what the joinee needs to accomplish in the first 30 days.",
    "The Plan & Task Service forwards the brief plus job title, team, start date and plan duration to the AI Orchestration Module.",
    "The AI Orchestration Module checks Redis for a cached response keyed by a hash of the input context; on a hit it returns the cached draft and skips the model call.",
    "On a cache miss, the module loads the current versioned prompt template, constructs the request and calls the LLM provider with a 20-second timeout, requesting structured JSON output.",
    "The LLM returns a JSON task array, which the module validates against the task output schema.",
    "If validation fails, the module retries once with a corrective instruction; if the retry also fails or times out, it returns a fallback signal and the client presents the manual task entry form with no data loss.",
    "Every invocation, successful or not, is written to the AI Run Logger with input, raw output, validation outcome, tokens and latency.",
    "The validated draft tasks are rendered in an editable grid; the plan remains in DRAFT and is not visible to the joinee.",
    "The manager edits titles, descriptions, categories, week numbers, day offsets and priorities, deletes unwanted rows and adds manual rows.",
    "The manager adds certifications with name, provider, URL, deadline and mandatory flag, and adds people to connect with including name, email, title and reason.",
    "The manager clicks Assign; the service converts each task's day offset into a concrete due date using the joinee's start date, transitions the plan to ACTIVE, records the approval in the audit trail, and marks the corresponding AI run as accepted along with its edit status.",
    "The joinee signs in and the Progress Service returns their active plan grouped by week, their certifications, their connection list and their completion percentage.",
    "The joinee browses or searches the Information Hub, which is served from the seeded info_resource table and requires no plan and no AI.",
    "The joinee updates task statuses, updates certification statuses and uploads proof documents to object storage, and marks connections as Scheduled or Met; each change is timestamped and audited.",
    "The Progress Service recomputes completion percentages and overdue counts, which surface on both the joinee dashboard and the manager's joinee list.",
    "The Scheduler runs daily, identifies items approaching or past their due date, and instructs the Notification Service to email reminders to joinees and escalations to the assigning manager.",
    "The manager reviews progress across all their joinees and either intervenes on blocked items or marks the plan COMPLETED once mandatory items are done.",
  ].join("\n"),
  integrations: [
    "Corporate OIDC identity provider (Google Workspace or Azure AD) for single sign-on and role claims",
    "Commercial LLM provider API for task generation, accessed through an internal abstraction layer with structured output enabled",
    "Transactional email service (SMTP) for due-date reminders and overdue escalations",
    "S3-compatible object storage for certification proof documents",
    "Redis for session storage and AI response caching",
    "External certification providers by outbound hyperlink only — no API integration, no content hosting",
    "IT ticketing system by outbound hyperlink only from the Information Hub — no API integration in v1",
    "Deferred: HRIS for automatic joinee creation and reporting-line sync",
    "Deferred: Slack for notifications",
    "Deferred: calendar API for scheduling introduction meetings",
  ].join("\n"),
  open_questions: [
    "What is the current baseline — how long does a manager spend today preparing an onboarding plan, and how many first-30-day tickets does IT receive per joinee?",
    "Has Information Security issued a position on sending job title and team to a third-party LLM provider, and is a self-hosted model required instead?",
    "Which LLM provider and model are approved, and what is the monthly budget cap?",
    "Who are the named content owners for each Information Hub category, and what review cadence will they commit to?",
    "Is the onboarding period fixed at 30 days, or must the plan duration be configurable per role?",
    "Should a joinee be able to see the Information Hub before their official start date, and if so how is their account provisioned early?",
    "Are certifications organisation-mandated and therefore standard across roles, or entirely manager-discretionary?",
    "Is certification proof upload actually required in v1, or is a self-declared status sufficient?",
    "What happens to an active plan when a joinee changes manager mid-onboarding?",
    "Can a joinee also be a manager — for example a senior hire who is themselves onboarding while owning direct reports?",
    "What is the expected hiring volume per month, which determines whether manual joinee creation is sustainable?",
    "Should the manager receive a digest email, or only exception-based overdue escalations?",
    "What are the data retention periods for completed plans, AI run logs and certification proof documents?",
    "Which deployment platform and environment tiers are available?",
    "Is there an existing internal design system or component library the frontend must adopt?",
  ].join("\n"),

  objectives: [
    {
      objective: "Give every new joinee a single dashboard covering their tasks, certifications, contacts and support information from day one",
      success_measure: "100% of new joinees have an approved, active onboarding plan visible on or before their start date",
    },
    {
      objective: "Cut the manager effort required to prepare an onboarding plan",
      success_measure: "Manager time to produce and assign a complete plan reduced from [TBD - baseline to confirm] to under 20 minutes per hire",
    },
    {
      objective: "Make onboarding progress visible to managers without manual follow-up",
      success_measure: "Manager can see per-joinee task, certification and connection completion status without messaging the joinee; 0 manual status-check requests needed",
    },
    {
      objective: "Ensure mandatory certifications are completed on time",
      success_measure: "95% of mandatory certifications completed by their stated deadline",
    },
    {
      objective: "Reduce repetitive access and support queries reaching IT and HR",
      success_measure: "Measurable reduction in first-30-day tickets and emails asking where to find access, tools or policy information [TBD - confirm baseline with IT]",
    },
    {
      objective: "Produce AI task drafts that managers find usable rather than rewrite wholesale",
      success_measure: "AI draft acceptance rate above 70%, with fewer than 30% of generated tasks edited or deleted before assignment",
    },
    {
      objective: "Standardise onboarding quality so it does not depend on which manager a joinee reports to",
      success_measure: "Variance in 30-day checklist completion rate across managers within [TBD] percentage points",
    },
  ],
  stakeholders: [
    { role: "Engineering Manager / Product Owner", interest: "Owns the product decision and the approval of scope; wants less time spent assembling onboarding plans and clear visibility of every joinee's progress" },
    { role: "Line Manager (primary user)", interest: "Needs to assign tasks, certifications and contacts quickly, and track completion without chasing people" },
    { role: "New Joinee (primary user)", interest: "Needs to know exactly what to do, by when, whom to talk to, and where to get help" },
    { role: "HR", interest: "Owns certification and policy content accuracy, and cares about time-to-productivity and early attrition" },
    { role: "IT Operations", interest: "Owns the accuracy of helpdesk, ticket-raising and access-request content in the Information Hub; wants fewer repetitive tickets" },
    { role: "Information Security", interest: "Must approve what employee data leaves the network to a third-party LLM provider, plus RBAC, audit trail and data retention" },
    { role: "Development Team", interest: "Needs unambiguous, testable requirements and a stable API contract before build starts" },
    { role: "Finance / Budget Owner", interest: "Controls LLM API spend and hosting cost" },
  ],
  target_users: [
    {
      persona: "Line Manager — manages one to five new joinees per cycle, time-poor, repeats the same onboarding setup for every hire",
      needs: "Generate a draft task list from a few lines of free text; edit and approve it in one screen; add certifications and people-to-connect manually; see at a glance who is behind and on what; never be blocked if the AI service is unavailable",
    },
    {
      persona: "New Joinee — first 30 days, unfamiliar with internal tools, processes and people; hesitant to ask basic questions repeatedly",
      needs: "One dashboard showing this week's tasks and what is overdue; a clear certification list with links and deadlines; names, emails and reasons for the five people to meet; and a self-service information hub answering how to raise an IT ticket, whom to email for access, and where policies live",
    },
  ],
  scope_deferred: [
    { item: "AI-generated recommendations for whom the joinee should connect with", why_deferred: "Requires a reliable org directory and raises fairness and bias concerns; manager entry is accurate and available on day one" },
    { item: "AI-written progress summaries for the manager dashboard", why_deferred: "Adds cost and a second approval surface for marginal benefit over a plain completion view in v1" },
    { item: "Retrieval-augmented AI assistant answering joinee questions over company documents", why_deferred: "Needs a document corpus, a vector store and a security review of document exposure; the static Information Hub covers the common questions at a fraction of the effort" },
    { item: "AI-suggested certifications based on role", why_deferred: "Certification lists are compliance-driven and must be authoritative; a wrong suggestion carries real risk" },
    { item: "HRIS integration for automatic joinee creation", why_deferred: "Hire volume is low enough for manual or CSV creation in v1; integration scope is unknown [TBD - confirm HRIS vendor]" },
    { item: "Slack and calendar integration for nudges and scheduling intro meetings", why_deferred: "Email reminders are sufficient for v1; adds two external dependencies" },
    { item: "Reusable role-based plan templates", why_deferred: "Wait for real usage data to show which task sets actually repeat before templating them" },
    { item: "Dedicated HR administrator role", why_deferred: "Two-role model keeps RBAC simple; HR content changes go through the seed file in v1" },
    { item: "Mobile native application", why_deferred: "Responsive web is adequate for a desk-based first 30 days" },
    { item: "Cross-organisation analytics dashboard and onboarding benchmarking", why_deferred: "No meaningful data exists until the system has run for at least one hiring cycle" },
  ],
  functional_requirements: [
    { description: "The system shall authenticate all users through the corporate OIDC identity provider and assign exactly one role, MANAGER or JOINEE, per user", priority: "M" },
    { description: "The system shall restrict a manager to viewing and modifying only the joinees mapped to them, rejecting all other access with an authorisation error", priority: "M" },
    { description: "The system shall allow a manager to create an onboarding plan for a joinee, capturing start date and plan duration, with the plan created in DRAFT status", priority: "M" },
    { description: "The system shall accept a free-text brief from the manager and send it, together with the joinee's job title, team, start date and plan duration, to the AI task generation service", priority: "M" },
    { description: "The system shall require the AI service to return tasks as structured JSON conforming to a defined schema, with each task carrying a title, description, category, week number, day offset, priority and optional subtasks", priority: "M" },
    { description: "The system shall validate every AI response against the defined JSON schema server-side and reject any non-conforming response", priority: "M" },
    { description: "The system shall retry a failed or invalid AI generation once, and on a second failure present the manual task entry form without loss of any data the manager has already entered", priority: "M" },
    { description: "The system shall limit a single AI generation to a maximum of 15 tasks", priority: "S" },
    { description: "The system shall present all AI-generated tasks in an editable grid where the manager can modify any field, delete rows and add new rows before assignment", priority: "M" },
    { description: "The system shall prevent any task from becoming visible to a joinee until the manager has explicitly approved and assigned the plan", priority: "M" },
    { description: "The system shall allow a manager to create, edit and delete tasks manually without invoking AI at any point", priority: "M" },
    { description: "The system shall calculate each task's due date as the joinee's start date plus the task's day offset at the moment of assignment", priority: "M" },
    { description: "The system shall transition a plan from DRAFT to ACTIVE on manager approval and make it visible to the joinee at that point", priority: "M" },
    { description: "The system shall allow a manager to add, edit and remove certifications for a joinee, capturing name, provider, URL, deadline and a mandatory flag", priority: "M" },
    { description: "The system shall allow a manager to add, edit and remove people for the joinee to connect with, capturing name, email, job title and a reason for the connection", priority: "M" },
    { description: "The system shall store connection contacts as free text rather than as references to system users, so that people outside the application can be listed", priority: "M" },
    { description: "The system shall display to the joinee their active plan grouped by week, showing task title, description, category, due date, priority and current status", priority: "M" },
    { description: "The system shall allow a joinee to change a task status between To Do, In Progress, Done and Blocked, recording the completion timestamp when set to Done", priority: "M" },
    { description: "The system shall allow a joinee to update certification status and upload a proof document for a completed certification", priority: "S" },
    { description: "The system shall allow a joinee to mark each listed person as Pending, Scheduled or Met, recording the date when set to Met", priority: "M" },
    { description: "The system shall display a joinee dashboard showing overall completion percentage, the current week's tasks, and all overdue items", priority: "M" },
    { description: "The system shall display a manager dashboard listing every joinee mapped to that manager with completion percentage and an overdue-item count", priority: "M" },
    { description: "The system shall present a read-only Information Hub to joinees, organised by category, covering IT helpdesk and ticket raising, access requests, accounts and tools, HR and payroll, workplace policies, security and compliance, and a general FAQ", priority: "M" },
    { description: "The system shall load Information Hub content from a versioned seed file into the database at deployment, so that content can be corrected without a code change", priority: "M" },
    { description: "The system shall provide a keyword search across Information Hub entry titles and body content", priority: "S" },
    { description: "The system shall allow an Information Hub entry to be deactivated so it is hidden from joinees without being deleted", priority: "C" },
    { description: "The system shall send the joinee an email reminder for tasks and certifications approaching their due date", priority: "S" },
    { description: "The system shall escalate overdue items to the assigning manager by email", priority: "S" },
    { description: "The system shall log every AI run with the manager identity, input brief, raw output, validation result, token usage, latency, and whether the output was accepted and whether it was edited", priority: "M" },
    { description: "The system shall maintain an audit trail of plan approval, task assignment, status changes and completions, recording actor and timestamp", priority: "S" },
    { description: "The system shall allow a manager to mark a plan COMPLETED once all mandatory items are done or the plan period has elapsed", priority: "C" },
    { description: "The system shall allow a joinee to add a note or comment against a task to flag a blocker to the manager", priority: "C" },
  ],
  non_functional_requirements: [
    { category: "Security", requirement: "All traffic over HTTPS; all API endpoints authenticated; no anonymous access to any resource including the Information Hub" },
    { category: "Security", requirement: "Authorisation enforced server-side on every request; a manager identifier in a request payload is never trusted as proof of ownership" },
    { category: "Security", requirement: "Uploaded certification proof files are virus-scanned, size-capped and restricted to an allowlist of file types" },
    { category: "Privacy", requirement: "Only the minimum context necessary — job title, team, start date, plan duration and the manager's brief — is transmitted to the LLM provider; no employee names, email addresses, identifiers or personal data are sent" },
    { category: "Privacy", requirement: "The LLM provider must be configured to exclude submitted data from model training, and the provider's retention policy must be documented and approved" },
    { category: "Data Retention", requirement: "Completed onboarding plans retained for [TBD] months; AI run logs retained for [TBD] months; certification proof documents retained per HR policy [TBD]" },
    { category: "Auditability", requirement: "Plan approval, task assignment, status changes and completions are recorded immutably with actor identity and UTC timestamp" },
    { category: "Auditability", requirement: "Every AI invocation is logged with prompt version, model identifier, input, raw output, validation outcome, token usage and latency, sufficient to reconstruct any generated plan" },
    { category: "Performance", requirement: "Non-AI API responses complete within 500 ms at p95 under expected load" },
    { category: "Performance", requirement: "Dashboard initial render within 2 seconds at p95 on a standard corporate network" },
    { category: "Performance", requirement: "AI task generation completes within 20 seconds at p95, with a hard timeout at 20 seconds after which the manual fallback is presented" },
    { category: "Reliability", requirement: "The application remains fully functional for every workflow except AI drafting when the LLM provider is degraded or unreachable; AI failure is never a blocking error" },
    { category: "Availability", requirement: "99.5% availability during business hours, excluding scheduled maintenance windows" },
    { category: "Scalability", requirement: "Supports at least 500 registered users and 100 concurrently active onboarding plans without architectural change" },
    { category: "Usability", requirement: "A manager can complete the full generate-edit-approve flow on a single screen without navigating away or losing entered data" },
    { category: "Usability", requirement: "A joinee can identify this week's outstanding tasks and all overdue items within one view of the dashboard, with no filtering required" },
    { category: "Accessibility", requirement: "WCAG 2.1 Level AA compliance for colour contrast, keyboard navigation, focus order and screen-reader labelling" },
    { category: "Compatibility", requirement: "Responsive layout supporting current versions of Chrome, Edge, Firefox and Safari, down to a 768 px viewport width" },
    { category: "Maintainability", requirement: "Prompt templates are stored as versioned files outside application code and are covered by golden-output regression tests" },
    { category: "Maintainability", requirement: "Information Hub content is editable via the seed file and applied without a code release or application redeploy" },
    { category: "Observability", requirement: "Structured application logging, health-check endpoints, and dashboards tracking AI acceptance rate, schema failure rate, latency and token spend" },
    { category: "Cost", requirement: "AI responses are cached by a hash of the input context so that identical briefs do not incur repeat token cost" },
    { category: "Localisation", requirement: "All user-facing strings externalised to resource files to permit future translation, though only English ships in v1" },
  ],
  risks: [
    { risk: "The AI generates plausible but irrelevant, generic or factually wrong tasks, and a rushed manager approves them unchecked", impact: "High", mitigation: "Force review through an editable grid with no bulk one-click approve; require an explicit assign action; surface a warning when a plan is assigned with zero edits; track and review edit rate weekly; iterate the prompt against a set of golden test cases" },
    { risk: "The LLM provider is unavailable, rate-limited or slow, blocking managers from assigning plans", impact: "High", mitigation: "Hard 20-second timeout, single retry, and an always-available manual entry form; AI is an accelerator, never a required path; monitor provider status and alert on elevated failure rates" },
    { risk: "Information Security rejects sending any employee-related context to a third-party LLM provider late in the build", impact: "High", mitigation: "Obtain a written data-boundary decision before development starts; design the prompt to carry only job title, team and dates with no names or identifiers; keep a self-hosted model as a documented contingency" },
    { risk: "Information Hub content becomes stale — wrong helpdesk address, dead ticket link, superseded policy — and actively misleads joinees", impact: "High", mitigation: "Assign a named content owner per category; record a last-reviewed date on every entry and display it; schedule a quarterly review; provide a one-click report-an-error action for joinees" },
    { risk: "Managers do not adopt the tool and revert to email and ad-hoc messages", impact: "High", mitigation: "Keep the generate-edit-approve flow under 20 minutes; pilot with two or three willing managers; gather feedback before wider rollout; make the manager dashboard the only place onboarding status is visible" },
    { risk: "LLM token spend exceeds budget through repeated regeneration", impact: "Medium", mitigation: "Cache by input hash; cap tasks per generation at 15; rate-limit regenerations per plan; alert on daily spend threshold; report cost per onboarded joinee" },
    { risk: "AI output fails schema validation frequently, degrading the manager experience", impact: "Medium", mitigation: "Use provider-native structured output or function calling; validate server-side; single retry with a corrective instruction; track first-attempt failure rate as a release gate" },
    { risk: "A manager accesses or modifies another manager's joinee data", impact: "High", mitigation: "Enforce ownership checks server-side on every endpoint; never derive authorisation from client-supplied identifiers; include cross-tenant access attempts in the automated test suite; log and alert on denied attempts" },
    { risk: "Joinees mark tasks complete without doing them, making progress data meaningless", impact: "Medium", mitigation: "Require proof upload for mandatory certifications; surface completion patterns to the manager; treat progress as a conversation prompt rather than an assurance mechanism" },
    { risk: "Certification deadlines are entered incorrectly or omitted, causing compliance gaps", impact: "Medium", mitigation: "Mark the mandatory flag and deadline as required fields for mandatory certifications; warn the manager when a mandatory certification has no deadline; escalate overdue mandatory items to the manager" },
    { risk: "Scope creep pulls additional AI capabilities back into v1", impact: "Medium", mitigation: "Deferred and permanently excluded AI uses are documented in this BRD; any addition requires a formal change request and re-approval" },
    { risk: "Vendor lock-in to a single LLM provider", impact: "Low", mitigation: "Abstract the model call behind an internal client interface; keep prompts and schema provider-agnostic; validate against a second provider before general availability" },
    { risk: "Low hiring volume means the system sits idle and the content decays before it proves value", impact: "Low", mitigation: "Pilot alongside a known intake; schedule content review independently of hiring activity" },
  ],
  system_components: [
    { name: "Manager Web Client", responsibility: "Joinee list with progress, plan editor with AI brief input and editable task grid, certification entry, people-to-connect entry, joinee detail view", interacts_with: "API Gateway" },
    { name: "Joinee Web Client", responsibility: "Dashboard with progress and overdue items, weekly plan view, task status updates, certification status and proof upload, connection tracking, Information Hub browse and search", interacts_with: "API Gateway" },
    { name: "API Gateway / Reverse Proxy", responsibility: "TLS termination, request routing, rate limiting, static asset serving", interacts_with: "Manager Web Client, Joinee Web Client, Spring Boot API" },
    { name: "Auth & RBAC Service", responsibility: "OIDC token validation, role resolution, and enforcement that a manager may only reach their own joinees", interacts_with: "Identity Provider, all internal services, PostgreSQL" },
    { name: "User Service", responsibility: "User records, role assignment, manager-to-joinee mapping, job title, team and start date", interacts_with: "PostgreSQL, Auth & RBAC Service" },
    { name: "Plan & Task Service", responsibility: "Plan lifecycle from DRAFT to ACTIVE to COMPLETED, task CRUD, due-date calculation from start date plus day offset, task status transitions", interacts_with: "PostgreSQL, AI Orchestration Module, Progress Service, Notification Service" },
    { name: "AI Orchestration Module", responsibility: "Builds the prompt from the manager brief and joinee context, calls the LLM with retry and timeout, validates the JSON response against the schema, returns a draft task list or triggers the manual fallback", interacts_with: "LLM Provider API, Prompt Template Store, AI Run Logger, Redis, Plan & Task Service" },
    { name: "Prompt Template Store", responsibility: "Holds versioned prompt templates and the task output JSON schema outside application code", interacts_with: "AI Orchestration Module" },
    { name: "AI Run Logger", responsibility: "Persists every AI invocation with input, raw output, validation outcome, tokens, latency, acceptance and edit status for cost tracking and quality measurement", interacts_with: "PostgreSQL, AI Orchestration Module" },
    { name: "Certification Service", responsibility: "Certification CRUD per plan, status transitions, proof upload handling, mandatory-item enforcement", interacts_with: "PostgreSQL, Object Storage, Notification Service" },
    { name: "Connection Service", responsibility: "Stores the manager-entered people list with name, email, title and reason, and tracks Pending, Scheduled and Met status", interacts_with: "PostgreSQL" },
    { name: "Information Hub Service", responsibility: "Serves read-only categorised static content and keyword search across titles and body text", interacts_with: "PostgreSQL" },
    { name: "Seed Loader", responsibility: "Loads Information Hub content from a versioned YAML or JSON file into the database at deployment time via migration", interacts_with: "PostgreSQL" },
    { name: "Progress Service", responsibility: "Computes completion percentages and overdue counts across tasks, certifications and connections for both dashboards", interacts_with: "PostgreSQL, Plan & Task Service, Certification Service, Connection Service" },
    { name: "Notification Service", responsibility: "Composes and dispatches due-date reminders to joinees and overdue escalations to managers", interacts_with: "Scheduler, Email Service, PostgreSQL" },
    { name: "Scheduler", responsibility: "Runs the daily job that detects upcoming and overdue items and triggers notifications", interacts_with: "Notification Service, Progress Service" },
    { name: "PostgreSQL", responsibility: "System of record for users, plans, tasks, certifications, connections, Information Hub content, AI runs and audit events", interacts_with: "All backend services" },
    { name: "Redis", responsibility: "Session storage and caching of AI responses keyed by input context hash", interacts_with: "Auth & RBAC Service, AI Orchestration Module" },
    { name: "Object Storage", responsibility: "Stores certification proof documents uploaded by joinees", interacts_with: "Certification Service" },
  ],
  timeline_phases: [
    {
      phase: "Phase 0 — Discovery and Documentation",
      content:
        "Finalise this BRD and the PRD; produce the ERD and data dictionary; publish the OpenAPI contract; define the RBAC matrix; wireframe the nine screens; obtain the Information Security data-boundary decision; collect signed-off Information Hub content from IT and HR",
      exit_criteria:
        "BRD and PRD approved by the decision audience; Information Security decision documented in writing; Information Hub content received and signed off; API contract published and agreed by backend and frontend",
    },
    {
      phase: "Phase 1 — Foundation",
      content:
        "Project scaffolding; PostgreSQL schema with Flyway migrations; OIDC authentication; MANAGER and JOINEE roles; server-side ownership enforcement; user creation and manager-to-joinee mapping; CI pipeline and deployment to a non-production environment",
      exit_criteria:
        "Both roles can sign in and see an empty role-appropriate shell; a manager cannot access another manager's joinee, proven by an automated test; pipeline deploys green to the test environment",
    },
    {
      phase: "Phase 2 — Information Hub",
      content:
        "info_resource table, seed loader and migration; category-based read-only Hub UI with accordion layout; keyword search; last-reviewed date displayed on every entry",
      exit_criteria:
        "A joinee can find IT helpdesk contact, ticket-raising steps and access-request contacts without assistance; content is updatable by editing the seed file and redeploying, with no code change; IT and HR confirm displayed content is accurate",
    },
    {
      phase: "Phase 3 — Manual Core",
      content:
        "Plan creation with DRAFT and ACTIVE states; manual task CRUD with due-date calculation; certification CRUD with proof upload; connection CRUD; joinee weekly plan view and status updates; progress calculation; manager joinee list",
      exit_criteria:
        "A manager can build, assign and track a complete onboarding plan end to end with no AI involved; a joinee can view everything assigned and update every status; progress figures reconcile against the underlying records",
    },
    {
      phase: "Phase 4 — AI Task Generation",
      content:
        "Prompt template store and output JSON schema; LLM client with retry, timeout and abstraction layer; server-side schema validation; editable draft grid; manual fallback path; AI run logging; Redis response caching; golden-output regression tests",
      exit_criteria:
        "A manager can generate, edit and assign a plan from a free-text brief; a forced LLM outage still permits full manual assignment; every run is logged with acceptance and edit status; first-attempt schema failure rate below 5% across the test set",
    },
    {
      phase: "Phase 5 — Notifications and Hardening",
      content:
        "Scheduled due-date reminders and overdue escalations; audit trail completion; accessibility pass to WCAG 2.1 AA; performance testing against stated targets; security review; observability dashboards for AI cost, latency and acceptance",
      exit_criteria:
        "Reminders and escalations verified in a staging run; accessibility audit passed; p95 latency targets met; security review closed with no high-severity findings",
    },
    {
      phase: "Phase 6 — Pilot and Rollout",
      content:
        "Pilot with two or three managers and their live joinees; collect feedback; tune prompts against real briefs; correct Information Hub content; then general availability with manager onboarding guidance",
      exit_criteria:
        "Pilot joinees complete onboarding through the tool; AI acceptance rate above 70% on real usage; pilot managers confirm the flow is faster than their previous process; no open high-severity defects",
    },
  ],
  additional_sections: [
    {
      title: "AI Boundary Statement",
      content:
        "Artificial intelligence is used for exactly one capability in this product: expanding a manager's short free-text brief into a structured draft task list. It is not used to select certifications, to recommend which people a joinee should meet, to summarise progress, or to generate or answer questions over Information Hub content. Those are either manager-entered or static seeded content by deliberate design. The governing rule is that AI proposes and the manager approves. No AI-generated content becomes visible to a joinee without an explicit manager approval action, and no workflow in the product depends on the model being available. This boundary exists so that accountability for what a new joinee is told stays with a named human, so that the system remains predictable and auditable, and so that operating cost stays low and bounded. Any proposal to extend AI beyond this boundary requires a formal change request and re-approval by the decision audience.",
    },
    {
      title: "AI Output Contract",
      content:
        "The AI must return a JSON object containing a single tasks array. Each element must provide: title (string, 5 to 100 characters); description (string, up to 500 characters); category (one of TECHNICAL_SETUP, ACCESS_AND_TOOLS, COMPLIANCE, TEAM_AND_PROCESS, ROLE_RAMP_UP, ADMIN); week_no (integer, 1 to 4); day_offset (integer, 0 to 30, expressed as days from the joinee's start date); priority (HIGH, MEDIUM or LOW); and an optional subtasks array of up to six short strings. A maximum of 15 tasks may be returned in a single generation. The response is validated server-side against this schema before it reaches the manager. Malformed responses trigger exactly one retry with a corrective instruction; a second failure surfaces the manual entry form. The AI never returns due dates — only day offsets — because concrete dates are derived at assignment time from the joinee's actual start date. This keeps generated content reusable and prevents date errors from propagating from the model.",
    },
    {
      title: "Information Hub Content Structure",
      content:
        "Information Hub content is stored in an info_resource table with the fields: id, category, title, body_md (Markdown), contact_email, link_url, display_order, last_reviewed_date and is_active. It is populated from a versioned seed file applied through a database migration, so that corrections require a content edit and redeploy rather than a code change. The six launch categories are: IT and Access, covering the helpdesk contact, how to raise a support ticket, ticket SLA and VPN setup; Accounts and Tools, covering email, Slack, Jira, GitHub and who approves each access request; HR and Payroll, covering payroll contact, leave policy, holiday calendar and benefits; Workplace, covering office timings, seating, ID cards and reimbursement; Security and Compliance, covering the code of conduct, data handling policy and mandatory reading; and FAQ, a plain list of who to ask for what. Each category has a named owner in IT or HR who is accountable for accuracy. The displayed last-reviewed date makes staleness visible to joinees rather than hiding it.",
    },
    {
      title: "Role and Permission Matrix",
      content:
        "MANAGER may: create and edit joinee records within their own reporting line; create, edit and delete plans, tasks, certifications and connections for their own joinees only; trigger AI task generation; approve and assign plans; view progress for their own joinees; and read the Information Hub. MANAGER may not: access any joinee outside their reporting line; edit Information Hub content; or modify a joinee's recorded task completions. JOINEE may: read their own active plan, certifications and connections; update the status of their own tasks, certifications and connections; upload their own certification proof; add notes to their own tasks; and read the Information Hub. JOINEE may not: view any other joinee's data; view draft plans; create, edit or delete tasks, certifications or connections; or invoke AI generation. All authorisation is enforced server-side on every request. Ownership is resolved from the authenticated token, never from an identifier supplied in the request body or query string.",
    },
    {
      title: "Definition of MVP",
      content:
        "The minimum viable product is Phases 0 through 4 inclusive: authentication with two roles and enforced ownership, the seeded Information Hub, full manual plan and task management, certifications, people to connect with, the joinee dashboard with progress and overdue visibility, the manager joinee list, and AI-assisted task drafting with a mandatory manager approval step and a working manual fallback. Notifications, the full audit trail, accessibility certification and observability dashboards are Phase 5 and are not required for the pilot. The MVP is considered viable when one manager can onboard one real joinee end to end using only this tool, and the joinee needs no email or verbal instruction to know what to do, what to complete, whom to meet, or where to get IT and HR help.",
    },
    {
      title: "Measuring AI Quality",
      content:
        "AI quality is measured by manager behaviour, not by subjective output review. Three metrics are tracked per generation and reported weekly. Acceptance rate is the share of generated tasks that survive to assignment without deletion, targeted above 70%. Edit rate is the share of assigned tasks whose fields were modified before assignment, targeted below 30%, where a high figure signals the prompt is producing content that is close but consistently wrong in a specific dimension. Regeneration rate is the number of times a manager re-runs generation for the same plan, where anything above one repeatedly indicates the first output is unusable. Schema validation failure rate on first attempt is tracked separately as a reliability rather than a quality signal, targeted below 5%. A set of golden briefs with expected output characteristics is maintained as a regression suite, and every prompt version change is evaluated against it before release.",
    },
    {
      title: "Out-of-Scope AI Uses and Why",
      content:
        "Four AI capabilities were considered and deliberately excluded from v1. AI-recommended people to connect with was excluded because it requires an accurate org directory the organisation does not currently expose, and because an algorithm choosing whom a new employee should build relationships with raises fairness concerns that outweigh the convenience; the manager already knows the answer. AI-generated progress summaries were excluded because a completion percentage with an overdue count conveys the same information deterministically, at zero cost and with no risk of a misleading summary. An AI assistant answering joinee questions over company documents was excluded because it requires a curated corpus, a vector store and a security review of which documents a joinee may see; the static Information Hub answers the common questions with guaranteed accuracy. AI-suggested certifications were excluded because certification requirements are compliance-driven, and a hallucinated or omitted mandatory certification carries genuine regulatory risk. Each remains a candidate for a later release once v1 usage data justifies the additional cost and review burden.",
    },
  ],
};
